# -*- coding: utf-8 -*-
"""Searching and Sorting Programming Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VBfAst2Xqo4x08O2xEFwMDmTSzT56K5
"""

#Searching and Sorting Programming Assignment
#March 30th, 2025

my_list = ["lions", "tigers", "turtles", "leopard", "elephant", "dog", "tree monkey"]
def count_starting_letters(list, letter):
    count = 0
    for word in list:
        if word[0] == letter:
            count = count + 1
    return count

def count_ending_letter(list, letter):
    count = 0
    for word in list:
        if word[len(word) - 1] == letter:
            count = count + 1
    return count

def find_word(list, word):
    index = 0
    for words in list:
        if words == word:
            index = index + 1
            return index
    return -1



count_starting_letters(my_list, "t")

count_ending_letter(my_list, "s")

#find_word(my_list, "tiger")

my_list = ["against", "forms", "belief", "government", "democratic", "movement", "understanding"]
def bubble_sort(list):
  counter = 0
  length = len(list) - 1
  for i in range(length):
        for k in range(len(list)-1):
            if list[k] > list[k+1]:
                counter = counter + 1
                list[k], list[k+1] = list[k+1],list[k]
  print("Bubble Sort Count: " + str(counter))
  return list

bubble_sort(my_list)

my_list = ["against", "forms", "belief", "government", "democratic", "movement", "understanding"]
def insertion_sort(list):
  count = 0
  for i in range(1, len(list)):
    current = list[i]
    while i > 0 and list[i - 1] > current:
      count = count + 1
      list[i] = list[i - 1]
      i = i - 1
      list[i] = current
  print("Insertion Sort Count: " + str(count))
  return list

insertion_sort(my_list)